[[redirects]]
  from = "https://api.football-data.org/v4/competitions/WC/matches?stage=${stage}"
  to = "https://fifa-api.netlify.app/.netlify/functions/knockouts/:splat"
  status = 200
  force = true
